#
# SPDX-License-Identifier: CC-BY-4.0
#

repository:
  name: agora-unknown_order
  description: agora-unknown_order
  homepage: https://wiki.hyperledger-labs.org/display/agora
  default_branch: main
  has_downloads: false
  has_issues: true
  has_projects: true
  has_wiki: true
  archived: false
  private: false
  allow_squash_merge: false
  allow_merge_commit: false
  allow_rebase_merge: true
